env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
plugins:
  - react
rules: {
    "react/jsx-uses-react": "off",
    "react/react-in-jsx-scope": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
}
ignorePatterns:
  - vite.config.ts
  - orval.config.ts
